<?php
/**
 * GetFundSchemeDetails200ResponseInnerReturns
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Apps\Fintech\Packages\Apis\Providers\Kuvera
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kuvera
 *
 * Unofficial read API specification for Kuvera.  See Introduction on left to get a summary.
 *
 * The version of the OpenAPI document: 
 * Contact: kuvera.api@captnemo.in
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Apps\Fintech\Packages\Apis\Providers\Kuvera\Model;

use \ArrayAccess;
use \Apps\Fintech\Packages\Apis\Providers\Kuvera\ObjectSerializer;

/**
 * GetFundSchemeDetails200ResponseInnerReturns Class Doc Comment
 *
 * @category Class
 * @package  Apps\Fintech\Packages\Apis\Providers\Kuvera
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetFundSchemeDetails200ResponseInnerReturns implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_fund_scheme_details_200_response_inner_returns';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'week_1' => 'float',
        'year_1' => 'float',
        'year_3' => 'float',
        'year_5' => 'float',
        'inception' => 'float',
        'date' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'week_1' => null,
        'year_1' => null,
        'year_3' => null,
        'year_5' => null,
        'inception' => null,
        'date' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'week_1' => false,
        'year_1' => false,
        'year_3' => false,
        'year_5' => false,
        'inception' => false,
        'date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'week_1' => 'week_1',
        'year_1' => 'year_1',
        'year_3' => 'year_3',
        'year_5' => 'year_5',
        'inception' => 'inception',
        'date' => 'date'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'week_1' => 'setWeek1',
        'year_1' => 'setYear1',
        'year_3' => 'setYear3',
        'year_5' => 'setYear5',
        'inception' => 'setInception',
        'date' => 'setDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'week_1' => 'getWeek1',
        'year_1' => 'getYear1',
        'year_3' => 'getYear3',
        'year_5' => 'getYear5',
        'inception' => 'getInception',
        'date' => 'getDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('week_1', $data ?? [], null);
        $this->setIfExists('year_1', $data ?? [], null);
        $this->setIfExists('year_3', $data ?? [], null);
        $this->setIfExists('year_5', $data ?? [], null);
        $this->setIfExists('inception', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['week_1'] === null) {
            $invalidProperties[] = "'week_1' can't be null";
        }
        if ($this->container['year_1'] === null) {
            $invalidProperties[] = "'year_1' can't be null";
        }
        if ($this->container['year_3'] === null) {
            $invalidProperties[] = "'year_3' can't be null";
        }
        if ($this->container['year_5'] === null) {
            $invalidProperties[] = "'year_5' can't be null";
        }
        if ($this->container['inception'] === null) {
            $invalidProperties[] = "'inception' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ((mb_strlen($this->container['date']) < 1)) {
            $invalidProperties[] = "invalid value for 'date', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets week_1
     *
     * @return float
     */
    public function getWeek1()
    {
        return $this->container['week_1'];
    }

    /**
     * Sets week_1
     *
     * @param float $week_1 week_1
     *
     * @return self
     */
    public function setWeek1($week_1)
    {
        if (is_null($week_1)) {
            throw new \InvalidArgumentException('non-nullable week_1 cannot be null');
        }
        $this->container['week_1'] = $week_1;

        return $this;
    }

    /**
     * Gets year_1
     *
     * @return float
     */
    public function getYear1()
    {
        return $this->container['year_1'];
    }

    /**
     * Sets year_1
     *
     * @param float $year_1 year_1
     *
     * @return self
     */
    public function setYear1($year_1)
    {
        if (is_null($year_1)) {
            throw new \InvalidArgumentException('non-nullable year_1 cannot be null');
        }
        $this->container['year_1'] = $year_1;

        return $this;
    }

    /**
     * Gets year_3
     *
     * @return float
     */
    public function getYear3()
    {
        return $this->container['year_3'];
    }

    /**
     * Sets year_3
     *
     * @param float $year_3 year_3
     *
     * @return self
     */
    public function setYear3($year_3)
    {
        if (is_null($year_3)) {
            throw new \InvalidArgumentException('non-nullable year_3 cannot be null');
        }
        $this->container['year_3'] = $year_3;

        return $this;
    }

    /**
     * Gets year_5
     *
     * @return float
     */
    public function getYear5()
    {
        return $this->container['year_5'];
    }

    /**
     * Sets year_5
     *
     * @param float $year_5 year_5
     *
     * @return self
     */
    public function setYear5($year_5)
    {
        if (is_null($year_5)) {
            throw new \InvalidArgumentException('non-nullable year_5 cannot be null');
        }
        $this->container['year_5'] = $year_5;

        return $this;
    }

    /**
     * Gets inception
     *
     * @return float
     */
    public function getInception()
    {
        return $this->container['inception'];
    }

    /**
     * Sets inception
     *
     * @param float $inception inception
     *
     * @return self
     */
    public function setInception($inception)
    {
        if (is_null($inception)) {
            throw new \InvalidArgumentException('non-nullable inception cannot be null');
        }
        $this->container['inception'] = $inception;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }

        if ((mb_strlen($date) < 1)) {
            throw new \InvalidArgumentException('invalid length for $date when calling GetFundSchemeDetails200ResponseInnerReturns., must be bigger than or equal to 1.');
        }

        $this->container['date'] = $date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


